### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by rhnvrd** [abgandar/Klingel#1]
hi there,
It seems that there is a problem with the makeFile, when I try to build with "make" I get this error:

this is command for build 
```
make all && \
make install
```

result :

```
MakeFile:4: ../pjprojec-2.7.1/build.mak: No such file or directory
make : *** No rule to make target '../pjproject-2.7.1/build.mak'
```

**Comment by abgandar** [comment]
That's probably because you need to download (and install) the [pjproject library](https://github.com/pjsip/pjproject) and adjust the first line in the Makefile according to the comment to point to the location of its source.
It should also work with the current version 2.13.
